### ISSUE TITLE
Upgrade master ubuntu template to 16.04

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#247]

**Comment by soffokl** [comment]
Since we are have support of multiple base images, I think, it's better to not replace original master, but add new ubuntu1604 image and keep update children templates on it. 
It will give us ability to keep workable old templates and add new parallel.
Anyway we need to get rid of master template, because it's not transparent for most of the users.

**Comment by akarasulu** [comment]
This is a good idea with parallel templates for both 14.04 and 16.04 as two masters. But I do not understand this "get rid of master template" comment can you elaborate?

**Comment by soffokl** [comment]
@akarasulu I mean we need to rename our current master template to something that make sense.
Currently we have only master template, and other templates based on it.
I suggestion to just rename it from "master" to "ubuntu1404", and add new "ubuntu1604".

**Comment by akarasulu** [comment]
OK has this been done?

**Comment by soffokl** [comment]
now we have ubuntu16 template and using it instead of master.
