### ISSUE TITLE
Automatic update/upgrade settings and mechanism

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#291]
I would like the SS console to expose settings to users to control the update/upgrade policy settings for the SS console (itself) and the RH snap. These settings however **MUST** be set within the subos to control the update/upgrade process because the SS management console cannot handle updating itself or the snap, it can **ONLY** expose a UI for users to modify such settings. 

Right now we're going to have a very simple policy which either enables or disables automatic updates along with a simple update check interval. We will elaborate on this so it's more robust as time progresses.

This will mean different things for release branches verses non-release branches:
- For release versions on tags **ONLY** new releases pushed to Gorjun will be used to upgrade and the default check interval should be every week on Thursday 7am GMT.
- For non-release versions on branches any updated snap or management template to Gorjun could trigger an upgrade, the default check interval should be daily at 7am GMT.

Based on these settings the subos should register a cron job that executes a Gorjun check for the snap or management template and if the installed MD5 differs from what is available in Gorjun it initiates the upgrade (or downgrade if we have a recall).

**Comment by akarasulu** [comment]
hey @tzununbekov can you please update?

**Comment by tzununbekov** [comment]
@akarasulu about Management upgrade in current state: SS periodically performs upgrade check and informs user if new version is available. In this case user should click on "update" button and SS upgrades itself with short SS restart but with user data persistance
about RH upgrade: as we said before, Snappy Ubuntu security policy forbids app manage itself and other apps, so in general we cannot manipulate RH snap from SS since all command from SS executes by agent and agent is a part of RH snap. This situation will be solved as soon as we'll be able to upload our snap to Snappy Store
