### ISSUE TITLE
Roaming across networks causes problems with old environments

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#427]
Mac laptop on home network created test env m3-single with 3 containers after a fresh install about 1hr ago. The environment worked well with EZ-SSH. 

Then switched laptop to 3G on phone. SS console came up nicely with new IP. However the old environment stopped working without ability to EZ-SSH. Then to check I created a new environment ap2-single and EZ-SSH worked just fine with it, while the old still remained disabled.

Then I restarted the Subutai VM. Both environments worked perfectly with EZ-SSH. Something must be left stale when switching.

**Comment by tzununbekov** [comment]
I'll try to reproduce this bug later today and update an issue

**Comment by tzununbekov** [comment]
Tried to reproduce described scenario with Subutai on Windows, didn't faced such behavior. Switched several times from home network to mobile 4G internet, all environments was accessible after short period for p2p reconnect
@akarasulu could you try to catch this bug again if possible, there is a chance that this bug was already fixed
