### ISSUE TITLE
Add a switch to use id of template to "subutai clone" command

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/subos#511]
We need to have an additional switch to **subutai clone** command which will be used by SS to clone containers, e.g.: **subutai clone -id  ${template_id} foo**
This will allow us to pass template ids to remote peers during cross peer environment creation to make the template selection precise.

**Comment by tzununbekov** [comment]
@Dilshat changed import and clone bindings merged to subos/dev
One note about command format - due to CLI library configuration that we use, command should look like this:
`subutai import id:a697e70f3fc538b4f4763588a7868388`
`subutai clone id:41a3db4a4481c97261e1aeb84abfb045 child`

*id:* tag is used to trigger operation by ID instead of name
