### ISSUE TITLE
Seems the ova file export is broken

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/subos#632]
Can no longer import the ova file. Seems to be thinking it has some vmware format files in it. Here's what an import attempt looks like:

<img width="389" alt="screen shot 2017-01-04 at 1 45 25 am" src="https://cloud.githubusercontent.com/assets/10051386/21625955/21a337dc-d217-11e6-840f-5201dabb1ef7.png">

This might be virtual box 5.1 problem.

**Comment by tzununbekov** [comment]
@akarasulu "ova file export" function uses vbox's internal command, so I don't think that "_it has some vmware format files in it_". Export part in autobuild was not changed for years, just checked on my machine - export/import worked fine.

There might be an issue specific to this host, for example, "VERR_NO_MEMORY" could be caused by lack of free RAM. Also, providing "subutai-1483482729.ova" may help us to locate the reason of import failure.

**Comment by p1gmale0n** [comment]
@akarasulu i think, it is some leak in VBox for macOS. i was this too..
as solution kill all processes from `ps -aef | grep VBox`
as i remember, it should be `VBoxSVC`, but i'm not totally sure

**Comment by akarasulu** [comment]
> There might be an issue specific to this host, for example, "VERR_NO_MEMORY" could be caused by lack of free RAM. Also, providing "subutai-1483482729.ova" may help us to locate the reason of import failure.

This was a huge 64GB Mac Pro with lots of free resources. I will try this again and give feedback especially after both your @tzununbekov a @p1gmale0n 's suggestions.

**Comment by tzununbekov** [comment]
@akarasulu any updates on this issue?
